# -*- coding: utf-8 -*-
"""DADO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CwS-cu5Ks1pM1yKnFkZl29wzMlI0ZJdM
"""

import matplotlib.pyplot as plt
import numpy as np
import random

def draw_dice(face_value):
    # Create a figure and a grid of subplots
    fig, ax = plt.subplots()

    # Define the points for each face value
    points = {
        1: [(1, 1)],
        2: [(0.5, 0.5), (1.5, 1.5)],
        3: [(0.5, 0.5), (1, 1), (1.5, 1.5)],
        4: [(0.5, 0.5), (0.5, 1.5), (1.5, 0.5), (1.5, 1.5)],
        5: [(0.5, 0.5), (0.5, 1.5), (1, 1), (1.5, 0.5), (1.5, 1.5)],
        6: [(0.5, 0.5), (0.5, 1), (0.5, 1.5), (1.5, 0.5), (1.5, 1), (1.5, 1.5)]
    }

    # Draw the square for the dice
    ax.add_patch(plt.Rectangle((0.5, 0.5), 1, 1, fill=None, edgecolor='k', lw=2))

    # Place the points for the specified face value
    for point in points[face_value]:
        ax.add_patch(plt.Circle(point, 0.1, color='black'))

    # Set limits and aspect
    ax.set_xlim(0, 2)
    ax.set_ylim(0, 2)
    ax.set_aspect('equal')
    ax.axis('off')  # Hide axes

    plt.show()

# Example of drawing a dice face with value 5
num_ = random.randint(1,7)
draw_dice(num_)

import random

n = random.randint(0,10)

print(n)