# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import math
import random

print("Buscar numero random\n")

n = random.randint(0, 500)

#print(n)

inp = int(input("Adivina el numero: "))
print()

while inp != n:

  if inp < n:
    print("Incorrecto numero Muy bajo")

  if inp > n:
    print("Incorrecto numero Muy alto")

  if inp == n:
    break;

  inp = int(input("Intenta de nuevo: "))
  print()


print(f"Numero correcto: {n}")
print("FIN")

print("CALCULADORA DE EDAD EN EL 2037")

name = input("Ingresa tu nombre: ")
print()
yr = int(input("En que año naciste? "))
print()

edad = 2023-yr
edad2 = 2037-yr

print(f"{name} tiene {edad} años y en el 2037 tendra {edad2} años")

print("Decide si un numero oes positivo o negativo\n")

n = int(input("Ingresa un numero: "))
print()

if n > 0:
  print("Numero positivo")
elif n == 0:
  print("Cero")
else:
    print("Numero negativo")

import math
import random

menu = 1
while (menu != 4):

  """
  Este es el menu de todos mis programas
  ENTRADAS: Por menu y por programa
  SALIDA: Independiente de cada menú
  """

  print(""" M E N U :
        ------------------
        1. Edad 2037
        2. Positivo - Negativo
        3. Random
        4. Salir
        """)

  menu = int(input("Elige una opcion: "))
  print()

  match menu:
    case 1:
      print("CALCULADORA DE EDAD EN EL 2037")

      name = input("Ingresa tu nombre: ")
      print()
      yr = int(input("En que año naciste? "))
      print()

      edad = 2023-yr
      edad2 = 2037-yr

      print(f"{name} tiene {edad} años y en el 2037 tendra {edad2} años")
    case 2:
      txt = "Decide si un numero es positivo o negativo\n"
      print(txt.upper())

      num = int(input("Ingresa un numero: "))
      print()

      if num > 0:
        print("Numero positivo")
      elif num == 0:
        print("Cero")
      else:
          print("Numero negativo")

    case 3:
      txt = "Buscar numero random\n"
      print(txt.upper())

      n = random.randint(0, 500)

      #print(n)

      inp = int(input("Adivina el numero: "))
      print()

      while inp != n:

        if inp < n:
          print("Incorrecto numero Muy bajo")

        if inp > n:
          print("Incorrecto numero Muy alto")

        if inp == n:
          break;

        inp = int(input("Intenta de nuevo: "))
        print()


      print(f"Numero correcto: {n}")
      print("FIN")

    case 4:
      print("Salió del menu")
      print("\nHASTA LUEGO")
      break;

print("Calificacion del curso:".upper())

exam = float(input("Ingrese la calificacion del examen: "))
project = float(input("Ingrese la calificacion del proyecto: "))


if (exam > 80) and (project > 80):
  grad = "Aprobado"
elif (exam > 70) and (project > 50):
  grad = "Condicionado"
else:
  grad = "Reprobado"

print(grad)

print("Temperatura\n".upper())

temp = float(input("Cual es la temperatura exterior? "))

if temp > 30:
  clot = "Playera sin mangas y short"
elif temp > 15:
  clot = "Playera y jeans"
elif temp < 0:
  clot = "Gabardina y calentadores"
else:
  clot = "Sweter y pantalon"

print(f"\nUsted debera vestir {clot} de acuerdo a la temperatura indicada")